-- Generated migration baseline for Zerra's Prisma schema.
CREATE TYPE "ScanStatus" AS ENUM ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED');
CREATE TYPE "FindingKind" AS ENUM ('SAST', 'SCA', 'SECRET', 'IAC');
CREATE TYPE "Severity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO');
CREATE TYPE "FindingStatus" AS ENUM ('OPEN', 'FIXED', 'IGNORED', 'NEEDS_HUMAN');
CREATE TYPE "FixStatus" AS ENUM ('PENDING', 'VERIFIED', 'FAILED', 'ISSUE_OPENED', 'PR_OPENED');
-- Use `prisma migrate deploy` to apply the full schema migration generated by Prisma.
