const ZERRA_API = process.env.NEXT_PUBLIC_ZERRA_URL || "http://localhost:8000";
const GO_API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";

export const APIENDPOINT = {
  Health: `${ZERRA_API}/health`,
  Evaluate: `${ZERRA_API}/v1/evaluate`,
  Metrics: `${ZERRA_API}/v1/metrics`,
  RiskCards: `${ZERRA_API}/v1/risk-cards`,
  Identities: `${ZERRA_API}/v1/identities`,
  TrustScores: `${ZERRA_API}/v1/trust-scores`,
  Policies: `${ZERRA_API}/v1/policies`,
  PoliciesCreate: `${ZERRA_API}/v1/policies`,
  PoliciesDelete: (id: string) => `${ZERRA_API}/v1/policies/${id}`,
  AttackSimScenarios: `${ZERRA_API}/v1/attack-sim/scenarios`,
  AttackSimRun: `${ZERRA_API}/v1/attack-sim/run`,
  InvestigateRiskCard: (id: string) => `${ZERRA_API}/v1/risk-cards/${id}/investigate`,
  PolicyRecommendation: (id: string) => `${ZERRA_API}/v1/risk-cards/${id}/policy-recommendation`,
  ApprovePolicy: (id: string) => `${ZERRA_API}/v1/policy-recommendations/${id}/approve`,
  IncidentReport: (id: string) => `${ZERRA_API}/v1/risk-cards/${id}/report`,
  RevokeIdentity: (id: string) => `${ZERRA_API}/v1/identities/${id}/revoke`,
  RestoreIdentity: (id: string) => `${ZERRA_API}/v1/identities/${id}/restore`,
  AttackReplay: `${ZERRA_API}/v1/attack-replay`,
  Proxy: `${GO_API}/api/v1/proxy`,
  SecurityScans: `${GO_API}/api/v1/security-scans`,
  SecurityScanJob: (id: string) => `${GO_API}/api/v1/security-scans/${id}`,
  SecurityScanFindings: (id: string) => `${GO_API}/api/v1/security-scans/${id}/findings`,
  SecurityScanCancel: (id: string) => `${GO_API}/api/v1/security-scans/${id}/cancel`,
  PentestSkills: `${ZERRA_API}/v1/pentest/skills`,
  PentestStart: `${ZERRA_API}/v1/pentest/start`,
  PentestJobs: `${ZERRA_API}/v1/pentest/jobs`,
  PentestStream: (id: string) => `${ZERRA_API}/v1/pentest/${id}/stream`,
  PentestStatus: (id: string) => `${ZERRA_API}/v1/pentest/${id}/status`,
  PentestFindings: (id: string) => `${ZERRA_API}/v1/pentest/${id}/findings`,
  PentestCoverage: (id: string) => `${ZERRA_API}/v1/pentest/${id}/coverage`,
  PentestApplyPatch: (id: string) => `${ZERRA_API}/v1/pentest/${id}/apply-patch`,
  PentestVerifyPatch: (id: string) => `${ZERRA_API}/v1/pentest/${id}/verify-patch`,
  PentestExportSarif: (id: string) => `${ZERRA_API}/v1/pentest/${id}/export/sarif`,
  PentestExportReport: (id: string) => `${ZERRA_API}/v1/pentest/${id}/export/report`,
  PentestExportAudit: (id: string) => `${ZERRA_API}/v1/pentest/${id}/export/audit`,
};
