package scanner

import (
 "bufio"; "bytes"; "context"; "encoding/json"; "errors"; "io"; "os"; "time"
 "github.com/DeveloperAromal/magma/internal/features/securityscan"
 "github.com/docker/docker/api/types/container"
 "github.com/docker/docker/api/types/strslice"
 "github.com/docker/docker/client"
 "github.com/docker/docker/pkg/stdcopy"
 "github.com/docker/go-units"
)
const maxOutput = 1 << 20
type DockerRunner struct { Client *client.Client; Image string }
func NewDockerRunner(cli *client.Client) DockerRunner { image:=os.Getenv("SENTRA_SCANNER_IMAGE");if image==""{image="sentra-api-security-runner:latest"};return DockerRunner{Client:cli,Image:image} }
func (r DockerRunner) Run(ctx context.Context, plan securityscan.ScanPlan)(securityscan.ScanReport,error){ payload,err:=json.Marshal(plan);if err!=nil{return securityscan.ScanReport{},err};timeoutCtx,cancel:=context.WithTimeout(ctx,60*time.Second);defer cancel();resp,err:=r.Client.ContainerCreate(timeoutCtx,&container.Config{Image:r.Image,Entrypoint:strslice.StrSlice{"/scanner"},Cmd:strslice.StrSlice{"--plan-stdin"},User:"65532:65532",OpenStdin:true,StdinOnce:true,AttachStdin:true,AttachStdout:true,AttachStderr:true,Tty:false},&container.HostConfig{ReadonlyRootfs:true,Privileged:false,AutoRemove:false,Resources:container.Resources{Memory:256*units.MiB,PidsLimit:int64Ptr(64),NanoCPUs:500000000},SecurityOpt:[]string{"no-new-privileges:true"},CapDrop:[]string{"ALL"}},nil,nil,"");if err!=nil{return securityscan.ScanReport{},err};defer r.Client.ContainerRemove(context.Background(),resp.ID,container.RemoveOptions{Force:true});attach,err:=r.Client.ContainerAttach(timeoutCtx,resp.ID,container.AttachOptions{Stream:true,Stdin:true,Stdout:true,Stderr:true});if err!=nil{return securityscan.ScanReport{},err};defer attach.Close();if err=r.Client.ContainerStart(timeoutCtx,resp.ID,container.StartOptions{});err!=nil{return securityscan.ScanReport{},err};if _,err=attach.Conn.Write(append(payload,'\n'));err!=nil{return securityscan.ScanReport{},err};attach.CloseWrite();wait,errCh:=r.Client.ContainerWait(timeoutCtx,resp.ID,container.WaitConditionNotRunning);select{case e:=<-errCh:if e!=nil{return securityscan.ScanReport{},e};case <-wait:case <-timeoutCtx.Done():return securityscan.ScanReport{},timeoutCtx.Err()};logs,err:=r.Client.ContainerLogs(timeoutCtx,resp.ID,container.LogsOptions{ShowStdout:true,ShowStderr:true});if err!=nil{return securityscan.ScanReport{},err};defer logs.Close();var stdout,stderr bytes.Buffer;if _,err=stdcopy.StdCopy(&stdout,&stderr,io.LimitReader(logs,maxOutput+1));err!=nil{return securityscan.ScanReport{},errors.New("could not decode scanner logs")};if stdout.Len()+stderr.Len()>maxOutput{return securityscan.ScanReport{},errors.New("scanner output exceeds limit")};return parseReport(stdout.Bytes()) }
func parseReport(output []byte)(securityscan.ScanReport,error){output=bytes.TrimSpace(output);if len(output)==0{return securityscan.ScanReport{},errors.New("scanner produced no JSON report")};var report securityscan.ScanReport;var envelope map[string]json.RawMessage;if err:=json.Unmarshal(output,&envelope);err==nil&&envelope["findings"]!=nil{if err=json.Unmarshal(output,&report);err==nil{return report,nil}};scanner:=bufio.NewScanner(bytes.NewReader(output));scanner.Buffer(make([]byte,1024),maxOutput);for scanner.Scan(){line:=bytes.TrimSpace(scanner.Bytes());if len(line)==0{continue};var finding securityscan.Finding;if err:=json.Unmarshal(line,&finding);err!=nil{return securityscan.ScanReport{},errors.New("scanner emitted invalid report")};report.Findings=append(report.Findings,finding)};if err:=scanner.Err();err!=nil||len(report.Findings)==0{return securityscan.ScanReport{},errors.New("scanner emitted invalid report")};return report,nil }
func int64Ptr(v int64)*int64{return &v}
