package securityscan

import (
 "context"; "database/sql"; "encoding/json"; "errors"; "time"
)
var ErrSubdomainNotFound = errors.New("registered subdomain not found")
type Repository interface { LookupProxyURL(context.Context,string)(string,error); CreateJob(context.Context,Job) (Job,error); UpdateJob(context.Context,Job) error; SaveFindings(context.Context,string,[]Finding) error; GetJob(context.Context,string)(Job,error); GetFindings(context.Context,string)([]Finding,error) }
type PostgresRepository struct { DB *sql.DB }
func (r PostgresRepository) LookupProxyURL(ctx context.Context, subdomain string)(string,error){ var u string; err:=r.DB.QueryRowContext(ctx,"SELECT api_base_url FROM proxy WHERE subdomain = $1",subdomain).Scan(&u); if errors.Is(err,sql.ErrNoRows){return "",ErrSubdomainNotFound}; return u,err }
func (r PostgresRepository) CreateJob(ctx context.Context,j Job)(Job,error){ err:=r.DB.QueryRowContext(ctx,`INSERT INTO security_scan_jobs(subdomain,target_url,status,mode,requested_at) VALUES($1,$2,$3,$4,$5) RETURNING id`,j.Subdomain,j.TargetURL,j.Status,j.Mode,j.RequestedAt).Scan(&j.ID); return j,err }
func (r PostgresRepository) UpdateJob(ctx context.Context,j Job)error{ _,err:=r.DB.ExecContext(ctx,`UPDATE security_scan_jobs SET status=$2,started_at=$3,completed_at=$4,total_checks=$5,passed_checks=$6,failed_checks=$7,warning_checks=$8,not_testable_checks=$9,error_message=$10 WHERE id=$1`,j.ID,j.Status,j.StartedAt,j.CompletedAt,j.TotalChecks,j.PassedChecks,j.FailedChecks,j.WarningChecks,j.NotTestableChecks,j.ErrorMessage); return err }
func (r PostgresRepository) SaveFindings(ctx context.Context,jobID string,fs []Finding)error{ tx,err:=r.DB.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback(); for _,f:=range fs{b,e:=json.Marshal(f.Evidence);if e!=nil{return e};if _,e=tx.ExecContext(ctx,`INSERT INTO security_scan_findings(job_id,owasp_id,title,severity,status,endpoint,method,evidence,remediation,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,jobID,f.OWASPID,f.Title,f.Severity,f.Status,f.Endpoint,f.Method,b,f.Remediation,time.Now().UTC());e!=nil{return e}};return tx.Commit() }
func (r PostgresRepository) GetJob(ctx context.Context,id string)(Job,error){ var j Job;err:=r.DB.QueryRowContext(ctx,`SELECT id,subdomain,target_url,status,mode,requested_at,started_at,completed_at,total_checks,passed_checks,failed_checks,warning_checks,not_testable_checks,error_message FROM security_scan_jobs WHERE id=$1`,id).Scan(&j.ID,&j.Subdomain,&j.TargetURL,&j.Status,&j.Mode,&j.RequestedAt,&j.StartedAt,&j.CompletedAt,&j.TotalChecks,&j.PassedChecks,&j.FailedChecks,&j.WarningChecks,&j.NotTestableChecks,&j.ErrorMessage);return j,err }
func (r PostgresRepository) GetFindings(ctx context.Context,id string)([]Finding,error){ rows,err:=r.DB.QueryContext(ctx,`SELECT id,job_id,owasp_id,title,severity,status,endpoint,method,evidence,remediation,created_at FROM security_scan_findings WHERE job_id=$1 ORDER BY owasp_id`,id);if err!=nil{return nil,err};defer rows.Close();var out []Finding;for rows.Next(){var f Finding;var evidence []byte;if err=rows.Scan(&f.ID,&f.JobID,&f.OWASPID,&f.Title,&f.Severity,&f.Status,&f.Endpoint,&f.Method,&evidence,&f.Remediation,&f.CreatedAt);err!=nil{return nil,err};if err=json.Unmarshal(evidence,&f.Evidence);err!=nil{return nil,err};out=append(out,f)};return out,rows.Err() }
