package securityscan

import (
 "context"; "errors"; "strings"; "sync"; "time"
)
var ErrSafeActiveDisabled=errors.New("safe_active scans are disabled")
var ErrCannotCancel=errors.New("only queued or running scans can be cancelled")
type Service struct { repo Repository; guard TargetGuard; runner Runner; limits Limits; safeActive bool; mu sync.Mutex; jobs map[string]context.CancelFunc; targetLocks map[string]*sync.Mutex }
func NewService(repo Repository,guard TargetGuard,runner Runner,limits Limits,safeActive bool)*Service{return &Service{repo:repo,guard:guard,runner:runner,limits:limits,safeActive:safeActive,jobs:map[string]context.CancelFunc{},targetLocks:map[string]*sync.Mutex{}}}
func(s *Service) Create(ctx context.Context,req CreateRequest)(Job,error){if req.Mode==""{req.Mode=Passive};if req.Mode!=Passive&&req.Mode!=SafeActive{return Job{},errors.New("invalid scan mode")};if req.Mode==SafeActive&&!s.safeActive{return Job{},ErrSafeActiveDisabled};target,err:=s.repo.LookupProxyURL(ctx,req.Subdomain);if err!=nil{return Job{},err};if err=s.guard.Validate(target);err!=nil{return Job{},err};job,err:=s.repo.CreateJob(ctx,Job{Subdomain:req.Subdomain,TargetURL:target,Status:Queued,Mode:req.Mode,RequestedAt:time.Now().UTC()});if err!=nil{return Job{},err};jobCtx,cancel:=context.WithCancel(context.Background());s.mu.Lock();s.jobs[job.ID]=cancel;s.mu.Unlock();go s.run(jobCtx,job);return job,nil}
func(s *Service) lockFor(target string)*sync.Mutex{s.mu.Lock();defer s.mu.Unlock();if s.targetLocks[target]==nil{s.targetLocks[target]=&sync.Mutex{}};return s.targetLocks[target]}
func(s *Service) run(ctx context.Context,job Job){lock:=s.lockFor(job.TargetURL);lock.Lock();defer lock.Unlock();now:=time.Now().UTC();job.Status=Running;job.StartedAt=&now;if err:=s.repo.UpdateJob(context.Background(),job);err!=nil{return};plan:=ScanPlan{JobID:job.ID,TargetURL:job.TargetURL,Mode:job.Mode,AllowedMethods:[]string{"GET","HEAD","OPTIONS"},RequestBudget:s.limits.RequestBudget,RateLimitPerSecond:s.limits.RateLimitPerSecond,KnownTestEndpoints:[]string{}};runCtx,cancel:=context.WithTimeout(ctx,s.limits.MaxDuration);defer cancel();report,err:=s.runner.Run(runCtx,plan);completed:=time.Now().UTC();job.CompletedAt=&completed;if err!=nil{message:=err.Error();job.Status=Failed;job.ErrorMessage=&message;_ = s.repo.UpdateJob(context.Background(),job);s.forget(job.ID);return};findings:=sanitize(report.Findings);if len(findings)==0{findings=DefaultFindings()};for _,f:=range findings{switch f.Status{case Pass:job.PassedChecks++;case FindingFail:job.FailedChecks++;case Warning:job.WarningChecks++;case NotTestable:job.NotTestableChecks++}};job.TotalChecks=len(findings);job.Status=Completed;if err=s.repo.SaveFindings(context.Background(),job.ID,findings);err!=nil{message:=err.Error();job.Status=Failed;job.ErrorMessage=&message};_ = s.repo.UpdateJob(context.Background(),job);s.forget(job.ID)}
func(s *Service) forget(id string){s.mu.Lock();defer s.mu.Unlock();delete(s.jobs,id)}
func(s *Service) Cancel(ctx context.Context,id string)error{job,err:=s.repo.GetJob(ctx,id);if err!=nil{return err};if job.Status!=Queued&&job.Status!=Running{return ErrCannotCancel};s.mu.Lock();cancel:=s.jobs[id];s.mu.Unlock();if cancel==nil{return ErrCannotCancel};cancel();return nil}
func(s *Service) Get(ctx context.Context,id string)(Job,error){return s.repo.GetJob(ctx,id)}
func(s *Service) Findings(ctx context.Context,id string)([]Finding,error){return s.repo.GetFindings(ctx,id)}
func sanitize(in []Finding)[]Finding{out:=make([]Finding,0,len(in));for _,f:=range in{f.Evidence=redactEvidence(f.Evidence);out=append(out,f)};return out}
func redactEvidence(e map[string]any)map[string]any{out:=map[string]any{};for k,v:=range e{if containsSecret(strings.ToLower(k)){out[k]="[REDACTED]";continue};if nested,ok:=v.(map[string]any);ok{out[k]=redactEvidence(nested)}else{out[k]=v}};return out}
func containsSecret(s string)bool{for _,needle:=range []string{"token","cookie","secret","password","authorization","body","ssn","salary","api_key"}{if strings.Contains(s,needle){return true}};return false}
